# schemas.py

from pydantic import BaseModel, Field
from enum import Enum
from typing import List, Optional

# --- Enums for Reliability (Context Engineering: Day 3) ---

class Channel(str, Enum):
    """
    Defines the specific social media channels the agent can target.
    This constrains the LLM's output to valid platform types.
    """
    LINKEDIN = "LINKEDIN"  # Professional, corporate audience
    STRAVA = "STRAVA"      # Casual, fitness/runner audience
    INTERNAL = "INTERNAL"  # Informal, internal company communications

class Tone(str, Enum):
    """
    Defines the required tone for a post, guiding the LLM's generation style.
    """
    PROFESSIONAL = "PROFESSIONAL"
    CASUAL = "CASUAL"
    MOTIVATIONAL = "MOTIVATIONAL"

class ApprovalStatus(str, Enum):
    """
    The outcome of the LLM-as-a-Judge evaluation.
    """
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    NEEDS_EDIT = "NEEDS_EDIT"


# --- Data Retrieval Schemas (Used by the "R" Tools) ---

class ActivitySummary(BaseModel):
    """
    Simulates a data structure from a Strava-style activity tracker.
    Used by the get_activity_summary tool.
    """
    event_name: str = Field(..., description="The name of the running event or activity.")
    date: str = Field(..., description="The date of the activity (e.g., '2025-11-29').")
    distance_km: float = Field(..., description="Total distance completed in kilometers.")
    duration_minutes: int = Field(..., description="Total time taken for the activity in minutes.")
    runners_participated: int = Field(..., description="Total number of team members who ran this activity.")


class FundraisingSummary(BaseModel):
    """
    Simulates a data structure from a JustGiving-style fundraising platform.
    Used by the get_fundraising_summary tool.
    """
    total_raised_usd: float = Field(..., description="Current total amount of money raised in USD.")
    campaign_target_usd: float = Field(..., description="The campaign's overall monetary target in USD.")
    percent_to_goal: float = Field(..., description="The percentage of the goal achieved (0.0 to 100.0).")
    latest_donor_name: str = Field(..., description="Name of the most recent donor for personalized thank yous.")
    is_milestone: bool = Field(..., description="True if a major milestone (e.g., 25%, 50%, 75%) was just hit.")


# --- Post Generation & Evaluation Schemas (Used by the "A" Tools) ---

class PostRequest(BaseModel):
    """
    The initial request parameters generated by the orchestrator agent 
    to guide the content creation step.
    """
    channel: Channel = Field(..., description="The target social media channel.")
    tone: Tone = Field(..., description="The required emotional tone of the post.")
    objective: str = Field(..., description="The specific goal: e.g., 'Celebrate 75% target' or 'Urge for more donations'.")
    context_data: dict = Field(..., description="A summary of the activity and fundraising data to include.")


class PostCandidate(BaseModel):
    """
    A single generated post option before it goes through the Quality Gate.
    This model enforces structure for the generation output.
    """
    channel: Channel = Field(..., description="The target channel for this candidate post.")
    text: str = Field(..., description="The full generated social media post, including hashtags.")
    rationale: str = Field(..., description="A short explanation of why this post is optimized for the target channel and data.")
    risk_flags: List[str] = Field(default_factory=list, description="List any brand safety, tone, or sensitivity risks (e.g., 'too aggressive CTA').")


class JudgeFeedback(BaseModel):
    """
    The structured output from the LLM-as-a-Judge tool (judge_post_quality).
    This is the core of our Evaluation (Day 4) implementation.
    """
    candidate_id: str = Field(..., description="A unique ID matching the PostCandidate being judged.")
    score_out_of_10: int = Field(..., description="The overall quality score (10 is perfect).")
    approval_status: ApprovalStatus = Field(..., description="The final decision: APPROVED, REJECTED, or NEEDS_EDIT.")
    reasoning: str = Field(..., description="A detailed explanation of the score and the decision.")
    edited_text: Optional[str] = Field(None, description="If status is NEEDS_EDIT, provides the corrected post text.")


# --- Observability Schema (Used for Logging the Trajectory) ---

class ReasoningTraceLog(BaseModel):
    """
    A model to record the agent's internal thought process and trajectory.
    This fulfills the Observability (Day 4) requirement and documents the 'Glass Box' view.
    """
    timestamp: str = Field(..., description="Time of the decision point.")
    step_number: int = Field(..., description="Corresponds to the 7-Step Trajectory.")
    justification: str = Field(..., description="The decision made and a natural language justification.")
    tool_called: Optional[str] = Field(None, description="The name of the tool called at this step, if any.")
    tool_output_summary: Optional[str] = Field(None, description="A brief summary of the tool's result.")
    
class AgentRunReport(BaseModel):
    """
    The final comprehensive report returned to the user, including the trajectory.
    """
    final_post: PostCandidate = Field(..., description="The single PostCandidate that passed the Quality Gate and was published.")
    channel_published: Channel = Field(..., description="The channel the post was simulated to be published to.")
    full_trajectory: List[ReasoningTraceLog] = Field(..., description="The complete, chronological log of the agent's 7-step reasoning process.")
